"""Kryon core — audit, config, exceptions, logger, paths, secrets.

Import order matters here: ``audit`` is imported before ``logger``
because ``logger`` depends on ``audit.redact_secrets`` for its
secret-redaction processor.
"""

from kryon.core.audit import (
    SCHEMA_SQL,
    AuditLog,
    get_audit_log,
    redact_secrets,
    reset_audit_log,
)
from kryon.core.config import (
    AuditConfig,
    ChannelConfig,
    CostConfig,
    KryonConfig,
    LLMConfig,
    MCPConfig,
    MCPServerConfig,
    NotificationConfig,
    OAuthConfig,
    SandboxConfig,
    ScopeConfig,
    SubagentDefaults,
    get_config_value,
    load_config,
    save_config,
    set_config_value,
)
from kryon.core.exceptions import (
    ActivityError,
    ApprovalError,
    AuditError,
    AuthorizationError,
    ConfigError,
    DryRunError,
    GraphError,
    KryonError,
    LLMError,
    LoopError,
    MCPError,
    NetworkError,
    RateLimitError,
    ScopeError,
    SecretError,
    SkillError,
    StateError,
    SubagentError,
    TargetError,
    ToolError,
)
from kryon.core.logger import (
    bind_log_context,
    clear_log_context,
    get_logger,
    get_target_logger,
    setup_logging,
    unbind_log_context,
)
from kryon.core.paths import (
    kryon_config_file,
    kryon_home,
    kryon_key_file,
    kryon_logs_dir,
    kryon_mcp_catalog_dir,
    kryon_profiles_dir,
    kryon_secrets_file,
    kryon_skill_bundles_dir,
    kryon_state_db_file,
    kryon_target_activity_log,
    kryon_target_audit_file,
    kryon_target_dir,
    kryon_target_graph_dir,
    kryon_target_reports_dir,
    kryon_target_scope_file,
    kryon_target_transcripts_dir,
    kryon_targets_dir,
    kryon_transcripts_dir,
    reset_kryon_home,
    set_kryon_home,
)
from kryon.core.secrets import (
    SecretsManager,
    delete_secret,
    get_secret,
    get_secrets_manager,
    has_secret,
    list_secrets,
    reset_secrets_manager,
    set_secret,
)

__all__ = [  # noqa: RUF022
    # Audit
    "AuditLog",
    "get_audit_log",
    "redact_secrets",
    "reset_audit_log",
    "SCHEMA_SQL",
    # Config
    "AuditConfig",
    "ChannelConfig",
    "CostConfig",
    "KryonConfig",
    "LLMConfig",
    "MCPConfig",
    "MCPServerConfig",
    "NotificationConfig",
    "OAuthConfig",
    "SandboxConfig",
    "ScopeConfig",
    "SubagentDefaults",
    "get_config_value",
    "load_config",
    "save_config",
    "set_config_value",
    # Exceptions
    "ActivityError",
    "ApprovalError",
    "AuditError",
    "AuthorizationError",
    "ConfigError",
    "DryRunError",
    "GraphError",
    "KryonError",
    "LLMError",
    "LoopError",
    "MCPError",
    "NetworkError",
    "RateLimitError",
    "ScopeError",
    "SecretError",
    "SkillError",
    "StateError",
    "SubagentError",
    "TargetError",
    "ToolError",
    # Logger
    "bind_log_context",
    "clear_log_context",
    "get_logger",
    "get_target_logger",
    "setup_logging",
    "unbind_log_context",
    # Paths
    "kryon_config_file",
    "kryon_home",
    "kryon_key_file",
    "kryon_logs_dir",
    "kryon_mcp_catalog_dir",
    "kryon_profiles_dir",
    "kryon_secrets_file",
    "kryon_skill_bundles_dir",
    "kryon_state_db_file",
    "kryon_target_activity_log",
    "kryon_target_audit_file",
    "kryon_target_dir",
    "kryon_target_graph_dir",
    "kryon_target_reports_dir",
    "kryon_target_scope_file",
    "kryon_target_transcripts_dir",
    "kryon_targets_dir",
    "kryon_transcripts_dir",
    "reset_kryon_home",
    "set_kryon_home",
    # Secrets
    "SecretsManager",
    "delete_secret",
    "get_secret",
    "get_secrets_manager",
    "has_secret",
    "list_secrets",
    "reset_secrets_manager",
    "set_secret",
]
